import test from 'node:test';
import assert from 'node:assert/strict';
import {createAdapter} from '../adapter.js';
function fixture(fetch){const cache=new Map(),storage=new Map(),events=[];const deps={core:{getRequestHeaders:()=>({'X-CSRF-Token':'test'}),eventSource:{emit:async(...args)=>events.push(args)},event_types:{WORLDINFO_UPDATED:'updated'}},wi:{worldInfoCache:cache},accountStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},fetch};return {deps,cache,storage,events}}
test('read uses authenticated native API and no-store',async()=>{const f=fixture(async(path,options)=>{assert.equal(path,'/api/worldinfo/get');assert.equal(options.headers['X-CSRF-Token'],'test');assert.equal(options.cache,'no-store');assert.deepEqual(JSON.parse(options.body),{name:'书'});return Response.json({entries:{}})});assert.deepEqual(await(await createAdapter(f.deps)).read('书'),{entries:{}})});
test('list native world names',async()=>{const f=fixture(async()=>Response.json({world_names:['书']}));assert.deepEqual(await(await createAdapter(f.deps)).list(),['书'])});
test('write success updates cache and emits notification',async()=>{const data={entries:{}};const f=fixture(async(path,o)=>{assert.equal(path,'/api/worldinfo/edit');assert.deepEqual(JSON.parse(o.body),{name:'书',data});return new Response('ok')});const a=await createAdapter(f.deps);await a.write('书',data);assert.deepEqual(a.cached('书'),data);assert.notEqual(a.cached('书'),data);assert.equal(f.events[0][0],'updated')});
test('failed write never changes cache or emits success',async()=>{const f=fixture(async()=>new Response('error',{status:500}));f.cache.set('书',{old:true});const a=await createAdapter(f.deps);await assert.rejects(a.write('书',{}),/500/);assert.deepEqual(a.cached('书'),{old:true});assert.equal(f.events.length,0)});
test('failed read reports HTTP error',async()=>{const f=fixture(async()=>new Response('',{status:403}));await assert.rejects((await createAdapter(f.deps)).read('书'),/403/)});
test('backups roundtrip in account-scoped storage',async()=>{const f=fixture(async()=>{});const a=await createAdapter(f.deps);assert.deepEqual(a.getBackups(),[]);a.putBackups([{id:'1'}]);assert.deepEqual(a.getBackups(),[{id:'1'}]);assert.equal(f.storage.size,1)});
test('invalid host capabilities rejected',async()=>{await assert.rejects(createAdapter({core:{},wi:{},accountStorage:{}}),/缺少世界书接口/)});
